### ISSUE TITLE
Date encoding/decoding broken

### ISSUE THREAD

**Issue by kirilltitov** [Flight-School/MessagePack#6]
Swift version 4.2.1

This code will crash
```swift
import Foundation
import MessagePack

let packed = try! MessagePackEncoder().encode(Date.distantPast)
print(packed)
let unpacked = try! MessagePackDecoder().decode(Date.self, from: packed)
print(unpacked)
```

If you change `Date.distantPast` to just `Date()`, it won't crash, but will decode incorrectly, to something like `1984-12-17 02:49:05` which is 34 years ago from now :)

If you comment out all custom `Date` codings in this package, everything works perfectly.

**Comment by mattt** [comment]
Thanks for bringing this to my attention, @kirilltitov.

The underlying issue was a typo in the code, where the format byte `d8` was provided instead of `c7` for `timestamp 96` messages. The crashing behavior in your provided code sample was caused by an unhandled error resulting from the decoder not knowing how to interpret the `c7` format byte.

This is now fixed by 49019b2, which also includes passing tests. Please let me know if you find any other issues!

**Comment by kirilltitov** [comment]
Not completely fixed. Current date (`Date()`) is still in 1984 (though `distantPast` and `distantFuture` are fixed)

**Comment by mattt** [comment]
Hmm... I can't reproduce this. I added a test to manually check the encoding logic with c78ad55, and it appears to work as expected according to the spec.

```
timestamp 32 stores the number of seconds that have elapsed since 1970-01-01 00:00:00 UTC
in an 32-bit unsigned integer:
+--------+--------+--------+--------+--------+--------+
|  0xd6  |   -1   |   seconds in 32-bit unsigned int  |
+--------+--------+--------+--------+--------+--------+
```

Likewise with the expected encoding and decoding tests, which produce `D6` `FF` and 32-bit-aligned 1.

```swift
let date = Date(timeIntervalSince1970: 1)
let value = try! encoder.encode(date)
// [0xD6, 0xFF, 0x00, 0x00, 0x00, 0x01]
```

If you're still having issues, can you please submit a new PR with a failing test?

**Comment by kirilltitov** [comment]
There you go — #7.
